### ISSUE TITLE
Solve image input image-name problem.

### ISSUE THREAD

**Issue by Saravanan-Jodavula** [Saravanan-Jodavula/Abstract-maker#2]
The app doesn't work if the input image-name contains spaces or special characters. Fix this issue.

**Comment by sanath1599** [comment]
I'll take this up. Assign it to me.

**Comment by Saravanan-Jodavula** [comment]
@sanath1599 Sure, assigned.

**Comment by Saravanan-Jodavula** [comment]
Great Job!! Everything's perfect!
